/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const NewsArticle = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'source' : IDL.Text,
  'timestamp' : Time,
});
export const PredictedMovement = IDL.Variant({
  'bullish' : IDL.Null,
  'bearish' : IDL.Null,
  'neutral' : IDL.Null,
});
export const DetectedChartPattern = IDL.Record({
  'patternName' : IDL.Text,
  'confidenceScore' : IDL.Float64,
});
export const StockPrediction = IDL.Record({
  'stockSymbol' : IDL.Text,
  'predictedMovement' : PredictedMovement,
  'predictionScore' : IDL.Float64,
  'diiSelling' : IDL.Float64,
  'confidenceLevel' : IDL.Float64,
  'fiiBuying' : IDL.Float64,
  'timestamp' : Time,
  'chartPatterns' : IDL.Vec(DetectedChartPattern),
  'newsSentimentScore' : IDL.Float64,
  'fiiSelling' : IDL.Float64,
  'diiBuying' : IDL.Float64,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'fetchNewsFromGoogle' : IDL.Func([], [], []),
  'getAllNewsArticles' : IDL.Func([], [IDL.Vec(NewsArticle)], ['query']),
  'getAllStockPredictions' : IDL.Func(
      [],
      [IDL.Vec(StockPrediction)],
      ['query'],
    ),
  'getAuthor' : IDL.Func([], [IDL.Text], ['query']),
  'getLatestNewsArticle' : IDL.Func([], [IDL.Opt(NewsArticle)], ['query']),
  'getLatestStockPrediction' : IDL.Func(
      [],
      [IDL.Opt(StockPrediction)],
      ['query'],
    ),
  'getNewsArticleById' : IDL.Func([IDL.Nat], [IDL.Opt(NewsArticle)], ['query']),
  'getStockPrediction' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(StockPrediction)],
      ['query'],
    ),
  'getStockPredictionById' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(StockPrediction)],
      ['query'],
    ),
  'getStockPredictionsBetweenTimes' : IDL.Func(
      [Time, Time],
      [IDL.Vec(StockPrediction)],
      ['query'],
    ),
  'getStockPredictionsBySymbol' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(StockPrediction)],
      ['query'],
    ),
  'storeNewsArticle' : IDL.Func([NewsArticle], [IDL.Nat], []),
  'storePrediction' : IDL.Func([StockPrediction], [], []),
  'storeStockPrediction' : IDL.Func([StockPrediction], [IDL.Nat], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const NewsArticle = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'source' : IDL.Text,
    'timestamp' : Time,
  });
  const PredictedMovement = IDL.Variant({
    'bullish' : IDL.Null,
    'bearish' : IDL.Null,
    'neutral' : IDL.Null,
  });
  const DetectedChartPattern = IDL.Record({
    'patternName' : IDL.Text,
    'confidenceScore' : IDL.Float64,
  });
  const StockPrediction = IDL.Record({
    'stockSymbol' : IDL.Text,
    'predictedMovement' : PredictedMovement,
    'predictionScore' : IDL.Float64,
    'diiSelling' : IDL.Float64,
    'confidenceLevel' : IDL.Float64,
    'fiiBuying' : IDL.Float64,
    'timestamp' : Time,
    'chartPatterns' : IDL.Vec(DetectedChartPattern),
    'newsSentimentScore' : IDL.Float64,
    'fiiSelling' : IDL.Float64,
    'diiBuying' : IDL.Float64,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'fetchNewsFromGoogle' : IDL.Func([], [], []),
    'getAllNewsArticles' : IDL.Func([], [IDL.Vec(NewsArticle)], ['query']),
    'getAllStockPredictions' : IDL.Func(
        [],
        [IDL.Vec(StockPrediction)],
        ['query'],
      ),
    'getAuthor' : IDL.Func([], [IDL.Text], ['query']),
    'getLatestNewsArticle' : IDL.Func([], [IDL.Opt(NewsArticle)], ['query']),
    'getLatestStockPrediction' : IDL.Func(
        [],
        [IDL.Opt(StockPrediction)],
        ['query'],
      ),
    'getNewsArticleById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(NewsArticle)],
        ['query'],
      ),
    'getStockPrediction' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(StockPrediction)],
        ['query'],
      ),
    'getStockPredictionById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(StockPrediction)],
        ['query'],
      ),
    'getStockPredictionsBetweenTimes' : IDL.Func(
        [Time, Time],
        [IDL.Vec(StockPrediction)],
        ['query'],
      ),
    'getStockPredictionsBySymbol' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(StockPrediction)],
        ['query'],
      ),
    'storeNewsArticle' : IDL.Func([NewsArticle], [IDL.Nat], []),
    'storePrediction' : IDL.Func([StockPrediction], [], []),
    'storeStockPrediction' : IDL.Func([StockPrediction], [IDL.Nat], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };