/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type MarketCallConfidenceScore = bigint;
export interface StockPrediction {
    stockSymbol: string;
    shortTermPriceTargetLower: number;
    riskFactors: Array<RiskFactor>;
    diiSelling: number;
    confidenceScore: number;
    shortTermPriceTargetUpper: number;
    priceDirection: PriceDirection;
    fiiBuying: number;
    timestamp: Time;
    technicalIndicators: Array<TechnicalIndicator>;
    newsSentimentScore: number;
    fiiSelling: number;
    aiRationale: string;
    diiBuying: number;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export type NewsSource = {
    __kind__: "bbc";
    bbc: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "yahooFinance";
    yahooFinance: null;
} | {
    __kind__: "cnbc";
    cnbc: null;
} | {
    __kind__: "mint";
    mint: null;
} | {
    __kind__: "bloomberg";
    bloomberg: null;
} | {
    __kind__: "economicTimes";
    economicTimes: null;
} | {
    __kind__: "reuters";
    reuters: null;
} | {
    __kind__: "barrons";
    barrons: null;
} | {
    __kind__: "marketWatch";
    marketWatch: null;
} | {
    __kind__: "fortune";
    fortune: null;
};
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface TechnicalIndicator {
    indicatorName: string;
    weightedScore: number;
}
export interface RiskFactor {
    impactLevel: number;
    description: string;
}
export interface DailyStockPick {
    trend: Variant_bullish_bearish;
    newsSentiment: number;
    fiiFlow: Variant_buy_sell_neutral;
    globalCues: Sentiment;
    callAction: Variant_buy_sell;
    sectorOverrideApplied: boolean;
    strikePrice: number;
    putAction: Variant_buy_sell;
    timestamp: Time;
    recommendedOption: Variant_ce_pe;
    sectorDirection: Variant_bullish_bearish_neutral;
    expiry: string;
    regulatorySignal: RegulatorySignal;
    worldMarketTrend: Variant_bullish_bearish_neutral;
    symbol: string;
    isHighVolume: boolean;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface NewsArticle {
    url: string;
    title: string;
    source: NewsSource;
    publishedDate: Time;
    sentiment: Sentiment;
    summary: string;
    category: NewsCategory;
}
export interface MarketCall {
    call: Variant_bullish_bearish_moderate;
    confidenceScore: MarketCallConfidenceScore;
    rationale: string;
    timestamp: Time;
    individualScores: {
        chartPatternSignal: number;
        fiiDiiFlowScore: number;
        regulatoryOverhang: number;
        newsSentimentScore: number;
    };
}
export interface PredictionAnalysis {
    predictionId: bigint;
    analyticalNotes: string;
    prediction: StockPrediction;
    newsArticles: Array<NewsArticle>;
    timestamp: Time;
}
export enum NewsCategory {
    regulatory = "regulatory",
    tariffs = "tariffs",
    indiaTradeDeals = "indiaTradeDeals",
    worldMarkets = "worldMarkets",
    general = "general",
    importExport = "importExport"
}
export enum Sentiment {
    negative = "negative",
    positive = "positive",
    neutral = "neutral"
}
export enum Variant_bullish_bearish {
    bullish = "bullish",
    bearish = "bearish"
}
export enum Variant_bullish_bearish_moderate {
    bullish = "bullish",
    bearish = "bearish",
    moderate = "moderate"
}
export enum Variant_bullish_bearish_neutral {
    bullish = "bullish",
    bearish = "bearish",
    neutral = "neutral"
}
export enum Variant_buy_sell {
    buy = "buy",
    sell = "sell"
}
export enum Variant_buy_sell_neutral {
    buy = "buy",
    sell = "sell",
    neutral = "neutral"
}
export enum Variant_ce_pe {
    ce = "ce",
    pe = "pe"
}
export interface backendInterface {
    fetchStockSummaryFromWikipedia(stockSymbol: string): Promise<string>;
    generateAndStoreDailyStockPicks(picks: Array<DailyStockPick>): Promise<void>;
    getAllMarketCalls(): Promise<Array<MarketCall>>;
    getAllNewsFeeds(): Promise<Array<NewsArticle>>;
    getAnalysisOfStockPredictions(analysisId: bigint): Promise<PredictionAnalysis | null>;
    getDaysMarketCall(marketCallId: bigint): Promise<MarketCall | null>;
    getHistoricalForecast(stockSymbol: string): Promise<Array<StockPrediction>>;
    getLastTradingDaysStockPicks(): Promise<Array<DailyStockPick> | null>;
    storeMarketCall(callType: Variant_bullish_bearish_moderate, confidenceScore: MarketCallConfidenceScore, rationale: string, newsSentimentScore: number, fiiDiiFlowScore: number, chartPatternSignal: number, regulatoryOverhang: number): Promise<bigint>;
    storeNewsArticle(title: string, source: NewsSource, category: NewsCategory, url: string, summary: string, sentiment: Sentiment): Promise<bigint>;
    storePredictionAnalysis(predictionId: bigint, analyticalNotes: string): Promise<bigint | null>;
    storePredictionForStock(symbol: string, priceDirection: PriceDirection, targetLower: number, targetUpper: number, confidence: number, rationale: string, riskFactors: Array<RiskFactor>, technicalIndicators: Array<TechnicalIndicator>, newsSentiment: number, fiiBuying: number, fiiSelling: number, diiBuying: number, diiSelling: number): Promise<bigint>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
}
import type { DailyStockPick as _DailyStockPick, MarketCall as _MarketCall, MarketCallConfidenceScore as _MarketCallConfidenceScore, NewsArticle as _NewsArticle, NewsCategory as _NewsCategory, NewsSource as _NewsSource, PredictionAnalysis as _PredictionAnalysis, PriceDirection as _PriceDirection, RegulatorySignal as _RegulatorySignal, RiskFactor as _RiskFactor, Sentiment as _Sentiment, StockPrediction as _StockPrediction, TechnicalIndicator as _TechnicalIndicator, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async fetchStockSummaryFromWikipedia(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchStockSummaryFromWikipedia(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchStockSummaryFromWikipedia(arg0);
            return result;
        }
    }
    async generateAndStoreDailyStockPicks(arg0: Array<DailyStockPick>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.generateAndStoreDailyStockPicks(to_candid_vec_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateAndStoreDailyStockPicks(to_candid_vec_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getAllMarketCalls(): Promise<Array<MarketCall>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMarketCalls();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMarketCalls();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllNewsFeeds(): Promise<Array<NewsArticle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNewsFeeds();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNewsFeeds();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnalysisOfStockPredictions(arg0: bigint): Promise<PredictionAnalysis | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalysisOfStockPredictions(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalysisOfStockPredictions(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDaysMarketCall(arg0: bigint): Promise<MarketCall | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDaysMarketCall(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDaysMarketCall(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHistoricalForecast(arg0: string): Promise<Array<StockPrediction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHistoricalForecast(arg0);
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHistoricalForecast(arg0);
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLastTradingDaysStockPicks(): Promise<Array<DailyStockPick> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLastTradingDaysStockPicks();
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLastTradingDaysStockPicks();
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async storeMarketCall(arg0: Variant_bullish_bearish_moderate, arg1: MarketCallConfidenceScore, arg2: string, arg3: number, arg4: number, arg5: number, arg6: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.storeMarketCall(to_candid_variant_n42(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeMarketCall(to_candid_variant_n42(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async storeNewsArticle(arg0: string, arg1: NewsSource, arg2: NewsCategory, arg3: string, arg4: string, arg5: Sentiment): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.storeNewsArticle(arg0, to_candid_NewsSource_n43(this._uploadFile, this._downloadFile, arg1), to_candid_NewsCategory_n45(this._uploadFile, this._downloadFile, arg2), arg3, arg4, to_candid_Sentiment_n47(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeNewsArticle(arg0, to_candid_NewsSource_n43(this._uploadFile, this._downloadFile, arg1), to_candid_NewsCategory_n45(this._uploadFile, this._downloadFile, arg2), arg3, arg4, to_candid_Sentiment_n47(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async storePredictionAnalysis(arg0: bigint, arg1: string): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.storePredictionAnalysis(arg0, arg1);
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storePredictionAnalysis(arg0, arg1);
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async storePredictionForStock(arg0: string, arg1: PriceDirection, arg2: number, arg3: number, arg4: number, arg5: string, arg6: Array<RiskFactor>, arg7: Array<TechnicalIndicator>, arg8: number, arg9: number, arg10: number, arg11: number, arg12: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.storePredictionForStock(arg0, to_candid_PriceDirection_n49(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storePredictionForStock(arg0, to_candid_PriceDirection_n49(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
}
function from_candid_DailyStockPick_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DailyStockPick): DailyStockPick {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_MarketCall_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MarketCall): MarketCall {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_NewsArticle_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NewsArticle): NewsArticle {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_NewsCategory_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NewsCategory): NewsCategory {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_NewsSource_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NewsSource): NewsSource {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_PredictionAnalysis_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PredictionAnalysis): PredictionAnalysis {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_PriceDirection_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PriceDirection): PriceDirection {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_RegulatorySignal_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RegulatorySignal): RegulatorySignal {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Sentiment_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Sentiment): Sentiment {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_StockPrediction_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StockPrediction): StockPrediction {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PredictionAnalysis]): PredictionAnalysis | null {
    return value.length === 0 ? null : from_candid_PredictionAnalysis_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MarketCall]): MarketCall | null {
    return value.length === 0 ? null : from_candid_MarketCall_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_DailyStockPick>]): Array<DailyStockPick> | null {
    return value.length === 0 ? null : from_candid_vec_n34(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    call: {
        bullish: null;
    } | {
        bearish: null;
    } | {
        moderate: null;
    };
    confidenceScore: _MarketCallConfidenceScore;
    rationale: string;
    timestamp: _Time;
    individualScores: {
        chartPatternSignal: number;
        fiiDiiFlowScore: number;
        regulatoryOverhang: number;
        newsSentimentScore: number;
    };
}): {
    call: Variant_bullish_bearish_moderate;
    confidenceScore: MarketCallConfidenceScore;
    rationale: string;
    timestamp: Time;
    individualScores: {
        chartPatternSignal: number;
        fiiDiiFlowScore: number;
        regulatoryOverhang: number;
        newsSentimentScore: number;
    };
} {
    return {
        call: from_candid_variant_n14(_uploadFile, _downloadFile, value.call),
        confidenceScore: value.confidenceScore,
        rationale: value.rationale,
        timestamp: value.timestamp,
        individualScores: value.individualScores
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    url: string;
    title: string;
    source: _NewsSource;
    publishedDate: _Time;
    sentiment: _Sentiment;
    summary: string;
    category: _NewsCategory;
}): {
    url: string;
    title: string;
    source: NewsSource;
    publishedDate: Time;
    sentiment: Sentiment;
    summary: string;
    category: NewsCategory;
} {
    return {
        url: value.url,
        title: value.title,
        source: from_candid_NewsSource_n18(_uploadFile, _downloadFile, value.source),
        publishedDate: value.publishedDate,
        sentiment: from_candid_Sentiment_n20(_uploadFile, _downloadFile, value.sentiment),
        summary: value.summary,
        category: from_candid_NewsCategory_n22(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    predictionId: bigint;
    analyticalNotes: string;
    prediction: _StockPrediction;
    newsArticles: Array<_NewsArticle>;
    timestamp: _Time;
}): {
    predictionId: bigint;
    analyticalNotes: string;
    prediction: StockPrediction;
    newsArticles: Array<NewsArticle>;
    timestamp: Time;
} {
    return {
        predictionId: value.predictionId,
        analyticalNotes: value.analyticalNotes,
        prediction: from_candid_StockPrediction_n27(_uploadFile, _downloadFile, value.prediction),
        newsArticles: from_candid_vec_n15(_uploadFile, _downloadFile, value.newsArticles),
        timestamp: value.timestamp
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    stockSymbol: string;
    shortTermPriceTargetLower: number;
    riskFactors: Array<_RiskFactor>;
    diiSelling: number;
    confidenceScore: number;
    shortTermPriceTargetUpper: number;
    priceDirection: _PriceDirection;
    fiiBuying: number;
    timestamp: _Time;
    technicalIndicators: Array<_TechnicalIndicator>;
    newsSentimentScore: number;
    fiiSelling: number;
    aiRationale: string;
    diiBuying: number;
}): {
    stockSymbol: string;
    shortTermPriceTargetLower: number;
    riskFactors: Array<RiskFactor>;
    diiSelling: number;
    confidenceScore: number;
    shortTermPriceTargetUpper: number;
    priceDirection: PriceDirection;
    fiiBuying: number;
    timestamp: Time;
    technicalIndicators: Array<TechnicalIndicator>;
    newsSentimentScore: number;
    fiiSelling: number;
    aiRationale: string;
    diiBuying: number;
} {
    return {
        stockSymbol: value.stockSymbol,
        shortTermPriceTargetLower: value.shortTermPriceTargetLower,
        riskFactors: value.riskFactors,
        diiSelling: value.diiSelling,
        confidenceScore: value.confidenceScore,
        shortTermPriceTargetUpper: value.shortTermPriceTargetUpper,
        priceDirection: from_candid_PriceDirection_n29(_uploadFile, _downloadFile, value.priceDirection),
        fiiBuying: value.fiiBuying,
        timestamp: value.timestamp,
        technicalIndicators: value.technicalIndicators,
        newsSentimentScore: value.newsSentimentScore,
        fiiSelling: value.fiiSelling,
        aiRationale: value.aiRationale,
        diiBuying: value.diiBuying
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    trend: {
        bullish: null;
    } | {
        bearish: null;
    };
    newsSentiment: number;
    fiiFlow: {
        buy: null;
    } | {
        sell: null;
    } | {
        neutral: null;
    };
    globalCues: {
        negative: null;
    } | {
        positive: null;
    } | {
        neutral: null;
    };
    callAction: {
        buy: null;
    } | {
        sell: null;
    };
    sectorOverrideApplied: boolean;
    strikePrice: number;
    putAction: {
        buy: null;
    } | {
        sell: null;
    };
    timestamp: _Time;
    recommendedOption: {
        ce: null;
    } | {
        pe: null;
    };
    sectorDirection: {
        bullish: null;
    } | {
        bearish: null;
    } | {
        neutral: null;
    };
    expiry: string;
    regulatorySignal: _RegulatorySignal;
    worldMarketTrend: {
        bullish: null;
    } | {
        bearish: null;
    } | {
        neutral: null;
    };
    symbol: string;
    isHighVolume: boolean;
}): {
    trend: Variant_bullish_bearish;
    newsSentiment: number;
    fiiFlow: Variant_buy_sell_neutral;
    globalCues: Sentiment;
    callAction: Variant_buy_sell;
    sectorOverrideApplied: boolean;
    strikePrice: number;
    putAction: Variant_buy_sell;
    timestamp: Time;
    recommendedOption: Variant_ce_pe;
    sectorDirection: Variant_bullish_bearish_neutral;
    expiry: string;
    regulatorySignal: RegulatorySignal;
    worldMarketTrend: Variant_bullish_bearish_neutral;
    symbol: string;
    isHighVolume: boolean;
} {
    return {
        trend: from_candid_variant_n37(_uploadFile, _downloadFile, value.trend),
        newsSentiment: value.newsSentiment,
        fiiFlow: from_candid_variant_n38(_uploadFile, _downloadFile, value.fiiFlow),
        globalCues: from_candid_variant_n21(_uploadFile, _downloadFile, value.globalCues),
        callAction: from_candid_variant_n39(_uploadFile, _downloadFile, value.callAction),
        sectorOverrideApplied: value.sectorOverrideApplied,
        strikePrice: value.strikePrice,
        putAction: from_candid_variant_n39(_uploadFile, _downloadFile, value.putAction),
        timestamp: value.timestamp,
        recommendedOption: from_candid_variant_n40(_uploadFile, _downloadFile, value.recommendedOption),
        sectorDirection: from_candid_variant_n30(_uploadFile, _downloadFile, value.sectorDirection),
        expiry: value.expiry,
        regulatorySignal: from_candid_RegulatorySignal_n41(_uploadFile, _downloadFile, value.regulatorySignal),
        worldMarketTrend: from_candid_variant_n30(_uploadFile, _downloadFile, value.worldMarketTrend),
        symbol: value.symbol,
        isHighVolume: value.isHighVolume
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bullish: null;
} | {
    bearish: null;
} | {
    moderate: null;
}): Variant_bullish_bearish_moderate {
    return "bullish" in value ? Variant_bullish_bearish_moderate.bullish : "bearish" in value ? Variant_bullish_bearish_moderate.bearish : "moderate" in value ? Variant_bullish_bearish_moderate.moderate : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bbc: null;
} | {
    other: string;
} | {
    yahooFinance: null;
} | {
    cnbc: null;
} | {
    mint: null;
} | {
    bloomberg: null;
} | {
    economicTimes: null;
} | {
    reuters: null;
} | {
    barrons: null;
} | {
    marketWatch: null;
} | {
    fortune: null;
}): {
    __kind__: "bbc";
    bbc: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "yahooFinance";
    yahooFinance: null;
} | {
    __kind__: "cnbc";
    cnbc: null;
} | {
    __kind__: "mint";
    mint: null;
} | {
    __kind__: "bloomberg";
    bloomberg: null;
} | {
    __kind__: "economicTimes";
    economicTimes: null;
} | {
    __kind__: "reuters";
    reuters: null;
} | {
    __kind__: "barrons";
    barrons: null;
} | {
    __kind__: "marketWatch";
    marketWatch: null;
} | {
    __kind__: "fortune";
    fortune: null;
} {
    return "bbc" in value ? {
        __kind__: "bbc",
        bbc: value.bbc
    } : "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "yahooFinance" in value ? {
        __kind__: "yahooFinance",
        yahooFinance: value.yahooFinance
    } : "cnbc" in value ? {
        __kind__: "cnbc",
        cnbc: value.cnbc
    } : "mint" in value ? {
        __kind__: "mint",
        mint: value.mint
    } : "bloomberg" in value ? {
        __kind__: "bloomberg",
        bloomberg: value.bloomberg
    } : "economicTimes" in value ? {
        __kind__: "economicTimes",
        economicTimes: value.economicTimes
    } : "reuters" in value ? {
        __kind__: "reuters",
        reuters: value.reuters
    } : "barrons" in value ? {
        __kind__: "barrons",
        barrons: value.barrons
    } : "marketWatch" in value ? {
        __kind__: "marketWatch",
        marketWatch: value.marketWatch
    } : "fortune" in value ? {
        __kind__: "fortune",
        fortune: value.fortune
    } : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    negative: null;
} | {
    positive: null;
} | {
    neutral: null;
}): Sentiment {
    return "negative" in value ? Sentiment.negative : "positive" in value ? Sentiment.positive : "neutral" in value ? Sentiment.neutral : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    regulatory: null;
} | {
    tariffs: null;
} | {
    indiaTradeDeals: null;
} | {
    worldMarkets: null;
} | {
    general: null;
} | {
    importExport: null;
}): NewsCategory {
    return "regulatory" in value ? NewsCategory.regulatory : "tariffs" in value ? NewsCategory.tariffs : "indiaTradeDeals" in value ? NewsCategory.indiaTradeDeals : "worldMarkets" in value ? NewsCategory.worldMarkets : "general" in value ? NewsCategory.general : "importExport" in value ? NewsCategory.importExport : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bullish: null;
} | {
    bearish: null;
} | {
    neutral: null;
}): Variant_bullish_bearish_neutral {
    return "bullish" in value ? Variant_bullish_bearish_neutral.bullish : "bearish" in value ? Variant_bullish_bearish_neutral.bearish : "neutral" in value ? Variant_bullish_bearish_neutral.neutral : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bullish: null;
} | {
    bearish: null;
}): Variant_bullish_bearish {
    return "bullish" in value ? Variant_bullish_bearish.bullish : "bearish" in value ? Variant_bullish_bearish.bearish : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    buy: null;
} | {
    sell: null;
} | {
    neutral: null;
}): Variant_buy_sell_neutral {
    return "buy" in value ? Variant_buy_sell_neutral.buy : "sell" in value ? Variant_buy_sell_neutral.sell : "neutral" in value ? Variant_buy_sell_neutral.neutral : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    buy: null;
} | {
    sell: null;
}): Variant_buy_sell {
    return "buy" in value ? Variant_buy_sell.buy : "sell" in value ? Variant_buy_sell.sell : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ce: null;
} | {
    pe: null;
}): Variant_ce_pe {
    return "ce" in value ? Variant_ce_pe.ce : "pe" in value ? Variant_ce_pe.pe : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MarketCall>): Array<MarketCall> {
    return value.map((x)=>from_candid_MarketCall_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NewsArticle>): Array<NewsArticle> {
    return value.map((x)=>from_candid_NewsArticle_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StockPrediction>): Array<StockPrediction> {
    return value.map((x)=>from_candid_StockPrediction_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DailyStockPick>): Array<DailyStockPick> {
    return value.map((x)=>from_candid_DailyStockPick_n35(_uploadFile, _downloadFile, x));
}
function to_candid_DailyStockPick_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DailyStockPick): _DailyStockPick {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_NewsCategory_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NewsCategory): _NewsCategory {
    return to_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function to_candid_NewsSource_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NewsSource): _NewsSource {
    return to_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function to_candid_PriceDirection_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PriceDirection): _PriceDirection {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_RegulatorySignal_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RegulatorySignal): _RegulatorySignal {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_Sentiment_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Sentiment): _Sentiment {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    trend: Variant_bullish_bearish;
    newsSentiment: number;
    fiiFlow: Variant_buy_sell_neutral;
    globalCues: Sentiment;
    callAction: Variant_buy_sell;
    sectorOverrideApplied: boolean;
    strikePrice: number;
    putAction: Variant_buy_sell;
    timestamp: Time;
    recommendedOption: Variant_ce_pe;
    sectorDirection: Variant_bullish_bearish_neutral;
    expiry: string;
    regulatorySignal: RegulatorySignal;
    worldMarketTrend: Variant_bullish_bearish_neutral;
    symbol: string;
    isHighVolume: boolean;
}): {
    trend: {
        bullish: null;
    } | {
        bearish: null;
    };
    newsSentiment: number;
    fiiFlow: {
        buy: null;
    } | {
        sell: null;
    } | {
        neutral: null;
    };
    globalCues: {
        negative: null;
    } | {
        positive: null;
    } | {
        neutral: null;
    };
    callAction: {
        buy: null;
    } | {
        sell: null;
    };
    sectorOverrideApplied: boolean;
    strikePrice: number;
    putAction: {
        buy: null;
    } | {
        sell: null;
    };
    timestamp: _Time;
    recommendedOption: {
        ce: null;
    } | {
        pe: null;
    };
    sectorDirection: {
        bullish: null;
    } | {
        bearish: null;
    } | {
        neutral: null;
    };
    expiry: string;
    regulatorySignal: _RegulatorySignal;
    worldMarketTrend: {
        bullish: null;
    } | {
        bearish: null;
    } | {
        neutral: null;
    };
    symbol: string;
    isHighVolume: boolean;
} {
    return {
        trend: to_candid_variant_n4(_uploadFile, _downloadFile, value.trend),
        newsSentiment: value.newsSentiment,
        fiiFlow: to_candid_variant_n5(_uploadFile, _downloadFile, value.fiiFlow),
        globalCues: to_candid_variant_n6(_uploadFile, _downloadFile, value.globalCues),
        callAction: to_candid_variant_n7(_uploadFile, _downloadFile, value.callAction),
        sectorOverrideApplied: value.sectorOverrideApplied,
        strikePrice: value.strikePrice,
        putAction: to_candid_variant_n7(_uploadFile, _downloadFile, value.putAction),
        timestamp: value.timestamp,
        recommendedOption: to_candid_variant_n8(_uploadFile, _downloadFile, value.recommendedOption),
        sectorDirection: to_candid_variant_n9(_uploadFile, _downloadFile, value.sectorDirection),
        expiry: value.expiry,
        regulatorySignal: to_candid_RegulatorySignal_n10(_uploadFile, _downloadFile, value.regulatorySignal),
        worldMarketTrend: to_candid_variant_n9(_uploadFile, _downloadFile, value.worldMarketTrend),
        symbol: value.symbol,
        isHighVolume: value.isHighVolume
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_bullish_bearish): {
    bullish: null;
} | {
    bearish: null;
} {
    return value == Variant_bullish_bearish.bullish ? {
        bullish: null
    } : value == Variant_bullish_bearish.bearish ? {
        bearish: null
    } : value;
}
function to_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_bullish_bearish_moderate): {
    bullish: null;
} | {
    bearish: null;
} | {
    moderate: null;
} {
    return value == Variant_bullish_bearish_moderate.bullish ? {
        bullish: null
    } : value == Variant_bullish_bearish_moderate.bearish ? {
        bearish: null
    } : value == Variant_bullish_bearish_moderate.moderate ? {
        moderate: null
    } : value;
}
function to_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "bbc";
    bbc: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "yahooFinance";
    yahooFinance: null;
} | {
    __kind__: "cnbc";
    cnbc: null;
} | {
    __kind__: "mint";
    mint: null;
} | {
    __kind__: "bloomberg";
    bloomberg: null;
} | {
    __kind__: "economicTimes";
    economicTimes: null;
} | {
    __kind__: "reuters";
    reuters: null;
} | {
    __kind__: "barrons";
    barrons: null;
} | {
    __kind__: "marketWatch";
    marketWatch: null;
} | {
    __kind__: "fortune";
    fortune: null;
}): {
    bbc: null;
} | {
    other: string;
} | {
    yahooFinance: null;
} | {
    cnbc: null;
} | {
    mint: null;
} | {
    bloomberg: null;
} | {
    economicTimes: null;
} | {
    reuters: null;
} | {
    barrons: null;
} | {
    marketWatch: null;
} | {
    fortune: null;
} {
    return value.__kind__ === "bbc" ? {
        bbc: value.bbc
    } : value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "yahooFinance" ? {
        yahooFinance: value.yahooFinance
    } : value.__kind__ === "cnbc" ? {
        cnbc: value.cnbc
    } : value.__kind__ === "mint" ? {
        mint: value.mint
    } : value.__kind__ === "bloomberg" ? {
        bloomberg: value.bloomberg
    } : value.__kind__ === "economicTimes" ? {
        economicTimes: value.economicTimes
    } : value.__kind__ === "reuters" ? {
        reuters: value.reuters
    } : value.__kind__ === "barrons" ? {
        barrons: value.barrons
    } : value.__kind__ === "marketWatch" ? {
        marketWatch: value.marketWatch
    } : value.__kind__ === "fortune" ? {
        fortune: value.fortune
    } : value;
}
function to_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NewsCategory): {
    regulatory: null;
} | {
    tariffs: null;
} | {
    indiaTradeDeals: null;
} | {
    worldMarkets: null;
} | {
    general: null;
} | {
    importExport: null;
} {
    return value == NewsCategory.regulatory ? {
        regulatory: null
    } : value == NewsCategory.tariffs ? {
        tariffs: null
    } : value == NewsCategory.indiaTradeDeals ? {
        indiaTradeDeals: null
    } : value == NewsCategory.worldMarkets ? {
        worldMarkets: null
    } : value == NewsCategory.general ? {
        general: null
    } : value == NewsCategory.importExport ? {
        importExport: null
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_buy_sell_neutral): {
    buy: null;
} | {
    sell: null;
} | {
    neutral: null;
} {
    return value == Variant_buy_sell_neutral.buy ? {
        buy: null
    } : value == Variant_buy_sell_neutral.sell ? {
        sell: null
    } : value == Variant_buy_sell_neutral.neutral ? {
        neutral: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Sentiment): {
    negative: null;
} | {
    positive: null;
} | {
    neutral: null;
} {
    return value == Sentiment.negative ? {
        negative: null
    } : value == Sentiment.positive ? {
        positive: null
    } : value == Sentiment.neutral ? {
        neutral: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_buy_sell): {
    buy: null;
} | {
    sell: null;
} {
    return value == Variant_buy_sell.buy ? {
        buy: null
    } : value == Variant_buy_sell.sell ? {
        sell: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_ce_pe): {
    ce: null;
} | {
    pe: null;
} {
    return value == Variant_ce_pe.ce ? {
        ce: null
    } : value == Variant_ce_pe.pe ? {
        pe: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_bullish_bearish_neutral): {
    bullish: null;
} | {
    bearish: null;
} | {
    neutral: null;
} {
    return value == Variant_bullish_bearish_neutral.bullish ? {
        bullish: null
    } : value == Variant_bullish_bearish_neutral.bearish ? {
        bearish: null
    } : value == Variant_bullish_bearish_neutral.neutral ? {
        neutral: null
    } : value;
}
function to_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<DailyStockPick>): Array<_DailyStockPick> {
    return value.map((x)=>to_candid_DailyStockPick_n2(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
