/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const RegulatorySignal = IDL.Variant({
  'negative' : IDL.Null,
  'positive' : IDL.Null,
  'neutral' : IDL.Null,
});
export const DailyStockPick = IDL.Record({
  'trend' : IDL.Variant({ 'bullish' : IDL.Null, 'bearish' : IDL.Null }),
  'newsSentiment' : IDL.Float64,
  'fiiFlow' : IDL.Variant({
    'buy' : IDL.Null,
    'sell' : IDL.Null,
    'neutral' : IDL.Null,
  }),
  'globalCues' : IDL.Variant({
    'negative' : IDL.Null,
    'positive' : IDL.Null,
    'neutral' : IDL.Null,
  }),
  'callAction' : IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null }),
  'sectorOverrideApplied' : IDL.Bool,
  'strikePrice' : IDL.Float64,
  'putAction' : IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null }),
  'timestamp' : Time,
  'recommendedOption' : IDL.Variant({ 'ce' : IDL.Null, 'pe' : IDL.Null }),
  'sectorDirection' : IDL.Variant({
    'bullish' : IDL.Null,
    'bearish' : IDL.Null,
    'neutral' : IDL.Null,
  }),
  'expiry' : IDL.Text,
  'regulatorySignal' : RegulatorySignal,
  'worldMarketTrend' : IDL.Variant({
    'bullish' : IDL.Null,
    'bearish' : IDL.Null,
    'neutral' : IDL.Null,
  }),
  'symbol' : IDL.Text,
  'isHighVolume' : IDL.Bool,
});
export const MarketCallConfidenceScore = IDL.Nat;
export const MarketCall = IDL.Record({
  'call' : IDL.Variant({
    'bullish' : IDL.Null,
    'bearish' : IDL.Null,
    'moderate' : IDL.Null,
  }),
  'confidenceScore' : MarketCallConfidenceScore,
  'rationale' : IDL.Text,
  'timestamp' : Time,
  'individualScores' : IDL.Record({
    'chartPatternSignal' : IDL.Float64,
    'fiiDiiFlowScore' : IDL.Float64,
    'regulatoryOverhang' : IDL.Float64,
    'newsSentimentScore' : IDL.Float64,
  }),
});
export const NewsSource = IDL.Variant({
  'bbc' : IDL.Null,
  'other' : IDL.Text,
  'yahooFinance' : IDL.Null,
  'cnbc' : IDL.Null,
  'mint' : IDL.Null,
  'bloomberg' : IDL.Null,
  'economicTimes' : IDL.Null,
  'reuters' : IDL.Null,
  'barrons' : IDL.Null,
  'marketWatch' : IDL.Null,
  'fortune' : IDL.Null,
});
export const Sentiment = IDL.Variant({
  'negative' : IDL.Null,
  'positive' : IDL.Null,
  'neutral' : IDL.Null,
});
export const NewsCategory = IDL.Variant({
  'regulatory' : IDL.Null,
  'tariffs' : IDL.Null,
  'indiaTradeDeals' : IDL.Null,
  'worldMarkets' : IDL.Null,
  'general' : IDL.Null,
  'importExport' : IDL.Null,
});
export const NewsArticle = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Text,
  'source' : NewsSource,
  'publishedDate' : Time,
  'sentiment' : Sentiment,
  'summary' : IDL.Text,
  'category' : NewsCategory,
});
export const RiskFactor = IDL.Record({
  'impactLevel' : IDL.Float64,
  'description' : IDL.Text,
});
export const PriceDirection = IDL.Variant({
  'bullish' : IDL.Null,
  'bearish' : IDL.Null,
  'neutral' : IDL.Null,
});
export const TechnicalIndicator = IDL.Record({
  'indicatorName' : IDL.Text,
  'weightedScore' : IDL.Float64,
});
export const StockPrediction = IDL.Record({
  'stockSymbol' : IDL.Text,
  'shortTermPriceTargetLower' : IDL.Float64,
  'riskFactors' : IDL.Vec(RiskFactor),
  'diiSelling' : IDL.Float64,
  'confidenceScore' : IDL.Float64,
  'shortTermPriceTargetUpper' : IDL.Float64,
  'priceDirection' : PriceDirection,
  'fiiBuying' : IDL.Float64,
  'timestamp' : Time,
  'technicalIndicators' : IDL.Vec(TechnicalIndicator),
  'newsSentimentScore' : IDL.Float64,
  'fiiSelling' : IDL.Float64,
  'aiRationale' : IDL.Text,
  'diiBuying' : IDL.Float64,
});
export const PredictionAnalysis = IDL.Record({
  'predictionId' : IDL.Nat,
  'analyticalNotes' : IDL.Text,
  'prediction' : StockPrediction,
  'newsArticles' : IDL.Vec(NewsArticle),
  'timestamp' : Time,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'fetchStockSummaryFromWikipedia' : IDL.Func([IDL.Text], [IDL.Text], []),
  'generateAndStoreDailyStockPicks' : IDL.Func(
      [IDL.Vec(DailyStockPick)],
      [],
      [],
    ),
  'getAllMarketCalls' : IDL.Func([], [IDL.Vec(MarketCall)], ['query']),
  'getAllNewsFeeds' : IDL.Func([], [IDL.Vec(NewsArticle)], ['query']),
  'getAnalysisOfStockPredictions' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(PredictionAnalysis)],
      ['query'],
    ),
  'getDaysMarketCall' : IDL.Func([IDL.Nat], [IDL.Opt(MarketCall)], ['query']),
  'getHistoricalForecast' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(StockPrediction)],
      ['query'],
    ),
  'getLastTradingDaysStockPicks' : IDL.Func(
      [],
      [IDL.Opt(IDL.Vec(DailyStockPick))],
      ['query'],
    ),
  'storeMarketCall' : IDL.Func(
      [
        IDL.Variant({
          'bullish' : IDL.Null,
          'bearish' : IDL.Null,
          'moderate' : IDL.Null,
        }),
        MarketCallConfidenceScore,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
      ],
      [IDL.Nat],
      [],
    ),
  'storeNewsArticle' : IDL.Func(
      [IDL.Text, NewsSource, NewsCategory, IDL.Text, IDL.Text, Sentiment],
      [IDL.Nat],
      [],
    ),
  'storePredictionAnalysis' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Opt(IDL.Nat)],
      [],
    ),
  'storePredictionForStock' : IDL.Func(
      [
        IDL.Text,
        PriceDirection,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
        IDL.Vec(RiskFactor),
        IDL.Vec(TechnicalIndicator),
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
      ],
      [IDL.Nat],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const RegulatorySignal = IDL.Variant({
    'negative' : IDL.Null,
    'positive' : IDL.Null,
    'neutral' : IDL.Null,
  });
  const DailyStockPick = IDL.Record({
    'trend' : IDL.Variant({ 'bullish' : IDL.Null, 'bearish' : IDL.Null }),
    'newsSentiment' : IDL.Float64,
    'fiiFlow' : IDL.Variant({
      'buy' : IDL.Null,
      'sell' : IDL.Null,
      'neutral' : IDL.Null,
    }),
    'globalCues' : IDL.Variant({
      'negative' : IDL.Null,
      'positive' : IDL.Null,
      'neutral' : IDL.Null,
    }),
    'callAction' : IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null }),
    'sectorOverrideApplied' : IDL.Bool,
    'strikePrice' : IDL.Float64,
    'putAction' : IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null }),
    'timestamp' : Time,
    'recommendedOption' : IDL.Variant({ 'ce' : IDL.Null, 'pe' : IDL.Null }),
    'sectorDirection' : IDL.Variant({
      'bullish' : IDL.Null,
      'bearish' : IDL.Null,
      'neutral' : IDL.Null,
    }),
    'expiry' : IDL.Text,
    'regulatorySignal' : RegulatorySignal,
    'worldMarketTrend' : IDL.Variant({
      'bullish' : IDL.Null,
      'bearish' : IDL.Null,
      'neutral' : IDL.Null,
    }),
    'symbol' : IDL.Text,
    'isHighVolume' : IDL.Bool,
  });
  const MarketCallConfidenceScore = IDL.Nat;
  const MarketCall = IDL.Record({
    'call' : IDL.Variant({
      'bullish' : IDL.Null,
      'bearish' : IDL.Null,
      'moderate' : IDL.Null,
    }),
    'confidenceScore' : MarketCallConfidenceScore,
    'rationale' : IDL.Text,
    'timestamp' : Time,
    'individualScores' : IDL.Record({
      'chartPatternSignal' : IDL.Float64,
      'fiiDiiFlowScore' : IDL.Float64,
      'regulatoryOverhang' : IDL.Float64,
      'newsSentimentScore' : IDL.Float64,
    }),
  });
  const NewsSource = IDL.Variant({
    'bbc' : IDL.Null,
    'other' : IDL.Text,
    'yahooFinance' : IDL.Null,
    'cnbc' : IDL.Null,
    'mint' : IDL.Null,
    'bloomberg' : IDL.Null,
    'economicTimes' : IDL.Null,
    'reuters' : IDL.Null,
    'barrons' : IDL.Null,
    'marketWatch' : IDL.Null,
    'fortune' : IDL.Null,
  });
  const Sentiment = IDL.Variant({
    'negative' : IDL.Null,
    'positive' : IDL.Null,
    'neutral' : IDL.Null,
  });
  const NewsCategory = IDL.Variant({
    'regulatory' : IDL.Null,
    'tariffs' : IDL.Null,
    'indiaTradeDeals' : IDL.Null,
    'worldMarkets' : IDL.Null,
    'general' : IDL.Null,
    'importExport' : IDL.Null,
  });
  const NewsArticle = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Text,
    'source' : NewsSource,
    'publishedDate' : Time,
    'sentiment' : Sentiment,
    'summary' : IDL.Text,
    'category' : NewsCategory,
  });
  const RiskFactor = IDL.Record({
    'impactLevel' : IDL.Float64,
    'description' : IDL.Text,
  });
  const PriceDirection = IDL.Variant({
    'bullish' : IDL.Null,
    'bearish' : IDL.Null,
    'neutral' : IDL.Null,
  });
  const TechnicalIndicator = IDL.Record({
    'indicatorName' : IDL.Text,
    'weightedScore' : IDL.Float64,
  });
  const StockPrediction = IDL.Record({
    'stockSymbol' : IDL.Text,
    'shortTermPriceTargetLower' : IDL.Float64,
    'riskFactors' : IDL.Vec(RiskFactor),
    'diiSelling' : IDL.Float64,
    'confidenceScore' : IDL.Float64,
    'shortTermPriceTargetUpper' : IDL.Float64,
    'priceDirection' : PriceDirection,
    'fiiBuying' : IDL.Float64,
    'timestamp' : Time,
    'technicalIndicators' : IDL.Vec(TechnicalIndicator),
    'newsSentimentScore' : IDL.Float64,
    'fiiSelling' : IDL.Float64,
    'aiRationale' : IDL.Text,
    'diiBuying' : IDL.Float64,
  });
  const PredictionAnalysis = IDL.Record({
    'predictionId' : IDL.Nat,
    'analyticalNotes' : IDL.Text,
    'prediction' : StockPrediction,
    'newsArticles' : IDL.Vec(NewsArticle),
    'timestamp' : Time,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'fetchStockSummaryFromWikipedia' : IDL.Func([IDL.Text], [IDL.Text], []),
    'generateAndStoreDailyStockPicks' : IDL.Func(
        [IDL.Vec(DailyStockPick)],
        [],
        [],
      ),
    'getAllMarketCalls' : IDL.Func([], [IDL.Vec(MarketCall)], ['query']),
    'getAllNewsFeeds' : IDL.Func([], [IDL.Vec(NewsArticle)], ['query']),
    'getAnalysisOfStockPredictions' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(PredictionAnalysis)],
        ['query'],
      ),
    'getDaysMarketCall' : IDL.Func([IDL.Nat], [IDL.Opt(MarketCall)], ['query']),
    'getHistoricalForecast' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(StockPrediction)],
        ['query'],
      ),
    'getLastTradingDaysStockPicks' : IDL.Func(
        [],
        [IDL.Opt(IDL.Vec(DailyStockPick))],
        ['query'],
      ),
    'storeMarketCall' : IDL.Func(
        [
          IDL.Variant({
            'bullish' : IDL.Null,
            'bearish' : IDL.Null,
            'moderate' : IDL.Null,
          }),
          MarketCallConfidenceScore,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
        ],
        [IDL.Nat],
        [],
      ),
    'storeNewsArticle' : IDL.Func(
        [IDL.Text, NewsSource, NewsCategory, IDL.Text, IDL.Text, Sentiment],
        [IDL.Nat],
        [],
      ),
    'storePredictionAnalysis' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Opt(IDL.Nat)],
        [],
      ),
    'storePredictionForStock' : IDL.Func(
        [
          IDL.Text,
          PriceDirection,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
          IDL.Vec(RiskFactor),
          IDL.Vec(TechnicalIndicator),
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
        ],
        [IDL.Nat],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };