/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailyStockPick {
  'trend' : { 'bullish' : null } |
    { 'bearish' : null },
  'newsSentiment' : number,
  'fiiFlow' : { 'buy' : null } |
    { 'sell' : null } |
    { 'neutral' : null },
  'globalCues' : { 'negative' : null } |
    { 'positive' : null } |
    { 'neutral' : null },
  'callAction' : { 'buy' : null } |
    { 'sell' : null },
  'sectorOverrideApplied' : boolean,
  'strikePrice' : number,
  'putAction' : { 'buy' : null } |
    { 'sell' : null },
  'timestamp' : Time,
  'recommendedOption' : { 'ce' : null } |
    { 'pe' : null },
  'sectorDirection' : { 'bullish' : null } |
    { 'bearish' : null } |
    { 'neutral' : null },
  'expiry' : string,
  'regulatorySignal' : RegulatorySignal,
  'worldMarketTrend' : { 'bullish' : null } |
    { 'bearish' : null } |
    { 'neutral' : null },
  'symbol' : string,
  'isHighVolume' : boolean,
}
export interface MarketCall {
  'call' : { 'bullish' : null } |
    { 'bearish' : null } |
    { 'moderate' : null },
  'confidenceScore' : MarketCallConfidenceScore,
  'rationale' : string,
  'timestamp' : Time,
  'individualScores' : {
    'chartPatternSignal' : number,
    'fiiDiiFlowScore' : number,
    'regulatoryOverhang' : number,
    'newsSentimentScore' : number,
  },
}
export type MarketCallConfidenceScore = bigint;
export interface NewsArticle {
  'url' : string,
  'title' : string,
  'source' : NewsSource,
  'publishedDate' : Time,
  'sentiment' : Sentiment,
  'summary' : string,
  'category' : NewsCategory,
}
export type NewsCategory = { 'regulatory' : null } |
  { 'tariffs' : null } |
  { 'indiaTradeDeals' : null } |
  { 'worldMarkets' : null } |
  { 'general' : null } |
  { 'importExport' : null };
export type NewsSource = { 'bbc' : null } |
  { 'other' : string } |
  { 'yahooFinance' : null } |
  { 'cnbc' : null } |
  { 'mint' : null } |
  { 'bloomberg' : null } |
  { 'economicTimes' : null } |
  { 'reuters' : null } |
  { 'barrons' : null } |
  { 'marketWatch' : null } |
  { 'fortune' : null };
export interface PredictionAnalysis {
  'predictionId' : bigint,
  'analyticalNotes' : string,
  'prediction' : StockPrediction,
  'newsArticles' : Array<NewsArticle>,
  'timestamp' : Time,
}
export type PriceDirection = { 'bullish' : null } |
  { 'bearish' : null } |
  { 'neutral' : null };
export type RegulatorySignal = { 'negative' : null } |
  { 'positive' : null } |
  { 'neutral' : null };
export interface RiskFactor { 'impactLevel' : number, 'description' : string }
export type Sentiment = { 'negative' : null } |
  { 'positive' : null } |
  { 'neutral' : null };
export interface StockPrediction {
  'stockSymbol' : string,
  'shortTermPriceTargetLower' : number,
  'riskFactors' : Array<RiskFactor>,
  'diiSelling' : number,
  'confidenceScore' : number,
  'shortTermPriceTargetUpper' : number,
  'priceDirection' : PriceDirection,
  'fiiBuying' : number,
  'timestamp' : Time,
  'technicalIndicators' : Array<TechnicalIndicator>,
  'newsSentimentScore' : number,
  'fiiSelling' : number,
  'aiRationale' : string,
  'diiBuying' : number,
}
export interface TechnicalIndicator {
  'indicatorName' : string,
  'weightedScore' : number,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'fetchStockSummaryFromWikipedia' : ActorMethod<[string], string>,
  'generateAndStoreDailyStockPicks' : ActorMethod<
    [Array<DailyStockPick>],
    undefined
  >,
  'getAllMarketCalls' : ActorMethod<[], Array<MarketCall>>,
  'getAllNewsFeeds' : ActorMethod<[], Array<NewsArticle>>,
  'getAnalysisOfStockPredictions' : ActorMethod<
    [bigint],
    [] | [PredictionAnalysis]
  >,
  'getDaysMarketCall' : ActorMethod<[bigint], [] | [MarketCall]>,
  'getHistoricalForecast' : ActorMethod<[string], Array<StockPrediction>>,
  'getLastTradingDaysStockPicks' : ActorMethod<
    [],
    [] | [Array<DailyStockPick>]
  >,
  'storeMarketCall' : ActorMethod<
    [
      { 'bullish' : null } |
        { 'bearish' : null } |
        { 'moderate' : null },
      MarketCallConfidenceScore,
      string,
      number,
      number,
      number,
      number,
    ],
    bigint
  >,
  'storeNewsArticle' : ActorMethod<
    [string, NewsSource, NewsCategory, string, string, Sentiment],
    bigint
  >,
  'storePredictionAnalysis' : ActorMethod<[bigint, string], [] | [bigint]>,
  'storePredictionForStock' : ActorMethod<
    [
      string,
      PriceDirection,
      number,
      number,
      number,
      string,
      Array<RiskFactor>,
      Array<TechnicalIndicator>,
      number,
      number,
      number,
      number,
      number,
    ],
    bigint
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];