/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface DetectedChartPattern {
    patternName: string;
    confidenceScore: number;
}
export interface StockPrediction {
    stockSymbol: string;
    predictedMovement: PredictedMovement;
    predictionScore: number;
    diiSelling: number;
    confidenceLevel: number;
    fiiBuying: number;
    timestamp: Time;
    chartPatterns: Array<DetectedChartPattern>;
    newsSentimentScore: number;
    fiiSelling: number;
    diiBuying: number;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface NewsArticle {
    title: string;
    content: string;
    source: string;
    timestamp: Time;
}
export interface http_header {
    value: string;
    name: string;
}
export enum PredictedMovement {
    bullish = "bullish",
    bearish = "bearish",
    neutral = "neutral"
}
export interface backendInterface {
    fetchNewsFromGoogle(): Promise<void>;
    getAllNewsArticles(): Promise<Array<NewsArticle>>;
    getAllStockPredictions(): Promise<Array<StockPrediction>>;
    getAuthor(): Promise<string>;
    getLatestNewsArticle(): Promise<NewsArticle | null>;
    getLatestStockPrediction(): Promise<StockPrediction | null>;
    getNewsArticleById(id: bigint): Promise<NewsArticle | null>;
    getStockPrediction(symbol: string): Promise<StockPrediction | null>;
    getStockPredictionById(id: bigint): Promise<StockPrediction | null>;
    getStockPredictionsBetweenTimes(startTime: Time, endTime: Time): Promise<Array<StockPrediction>>;
    getStockPredictionsBySymbol(symbol: string): Promise<Array<StockPrediction>>;
    storeNewsArticle(article: NewsArticle): Promise<bigint>;
    storeStockPrediction(prediction: StockPrediction): Promise<bigint>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
}
import type { DetectedChartPattern as _DetectedChartPattern, NewsArticle as _NewsArticle, PredictedMovement as _PredictedMovement, StockPrediction as _StockPrediction, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async fetchNewsFromGoogle(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchNewsFromGoogle();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchNewsFromGoogle();
            return result;
        }
    }
    async getAllNewsArticles(): Promise<Array<NewsArticle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNewsArticles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNewsArticles();
            return result;
        }
    }
    async getAllStockPredictions(): Promise<Array<StockPrediction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStockPredictions();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStockPredictions();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAuthor(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuthor();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuthor();
            return result;
        }
    }
    async getLatestNewsArticle(): Promise<NewsArticle | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestNewsArticle();
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestNewsArticle();
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLatestStockPrediction(): Promise<StockPrediction | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestStockPrediction();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestStockPrediction();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNewsArticleById(arg0: bigint): Promise<NewsArticle | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNewsArticleById(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNewsArticleById(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStockPrediction(arg0: string): Promise<StockPrediction | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStockPrediction(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStockPrediction(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStockPredictionById(arg0: bigint): Promise<StockPrediction | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStockPredictionById(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStockPredictionById(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStockPredictionsBetweenTimes(arg0: Time, arg1: Time): Promise<Array<StockPrediction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStockPredictionsBetweenTimes(arg0, arg1);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStockPredictionsBetweenTimes(arg0, arg1);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStockPredictionsBySymbol(arg0: string): Promise<Array<StockPrediction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStockPredictionsBySymbol(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStockPredictionsBySymbol(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async storeNewsArticle(arg0: NewsArticle): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.storeNewsArticle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeNewsArticle(arg0);
            return result;
        }
    }
    async storeStockPrediction(arg0: StockPrediction): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.storeStockPrediction(to_candid_StockPrediction_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeStockPrediction(to_candid_StockPrediction_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
}
function from_candid_PredictedMovement_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PredictedMovement): PredictedMovement {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_StockPrediction_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StockPrediction): StockPrediction {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_NewsArticle]): NewsArticle | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StockPrediction]): StockPrediction | null {
    return value.length === 0 ? null : from_candid_StockPrediction_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    stockSymbol: string;
    predictedMovement: _PredictedMovement;
    predictionScore: number;
    diiSelling: number;
    confidenceLevel: number;
    fiiBuying: number;
    timestamp: _Time;
    chartPatterns: Array<_DetectedChartPattern>;
    newsSentimentScore: number;
    fiiSelling: number;
    diiBuying: number;
}): {
    stockSymbol: string;
    predictedMovement: PredictedMovement;
    predictionScore: number;
    diiSelling: number;
    confidenceLevel: number;
    fiiBuying: number;
    timestamp: Time;
    chartPatterns: Array<DetectedChartPattern>;
    newsSentimentScore: number;
    fiiSelling: number;
    diiBuying: number;
} {
    return {
        stockSymbol: value.stockSymbol,
        predictedMovement: from_candid_PredictedMovement_n4(_uploadFile, _downloadFile, value.predictedMovement),
        predictionScore: value.predictionScore,
        diiSelling: value.diiSelling,
        confidenceLevel: value.confidenceLevel,
        fiiBuying: value.fiiBuying,
        timestamp: value.timestamp,
        chartPatterns: value.chartPatterns,
        newsSentimentScore: value.newsSentimentScore,
        fiiSelling: value.fiiSelling,
        diiBuying: value.diiBuying
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bullish: null;
} | {
    bearish: null;
} | {
    neutral: null;
}): PredictedMovement {
    return "bullish" in value ? PredictedMovement.bullish : "bearish" in value ? PredictedMovement.bearish : "neutral" in value ? PredictedMovement.neutral : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StockPrediction>): Array<StockPrediction> {
    return value.map((x)=>from_candid_StockPrediction_n2(_uploadFile, _downloadFile, x));
}
function to_candid_PredictedMovement_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PredictedMovement): _PredictedMovement {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_StockPrediction_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StockPrediction): _StockPrediction {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    stockSymbol: string;
    predictedMovement: PredictedMovement;
    predictionScore: number;
    diiSelling: number;
    confidenceLevel: number;
    fiiBuying: number;
    timestamp: Time;
    chartPatterns: Array<DetectedChartPattern>;
    newsSentimentScore: number;
    fiiSelling: number;
    diiBuying: number;
}): {
    stockSymbol: string;
    predictedMovement: _PredictedMovement;
    predictionScore: number;
    diiSelling: number;
    confidenceLevel: number;
    fiiBuying: number;
    timestamp: _Time;
    chartPatterns: Array<_DetectedChartPattern>;
    newsSentimentScore: number;
    fiiSelling: number;
    diiBuying: number;
} {
    return {
        stockSymbol: value.stockSymbol,
        predictedMovement: to_candid_PredictedMovement_n10(_uploadFile, _downloadFile, value.predictedMovement),
        predictionScore: value.predictionScore,
        diiSelling: value.diiSelling,
        confidenceLevel: value.confidenceLevel,
        fiiBuying: value.fiiBuying,
        timestamp: value.timestamp,
        chartPatterns: value.chartPatterns,
        newsSentimentScore: value.newsSentimentScore,
        fiiSelling: value.fiiSelling,
        diiBuying: value.diiBuying
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PredictedMovement): {
    bullish: null;
} | {
    bearish: null;
} | {
    neutral: null;
} {
    return value == PredictedMovement.bullish ? {
        bullish: null
    } : value == PredictedMovement.bearish ? {
        bearish: null
    } : value == PredictedMovement.neutral ? {
        neutral: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
